services:
  - type: web
    name: ai-resume-editor-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false  # This will be set manually in Render dashboard
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main 